config/routes.rb
Rails.application.routes.draw do
  root 'books#top'
  get 'top' => 'books#top'
  get '/home/about' => 'books#about'
  devise_for :users
  resources :books do
  	resource :post_comments
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	has_many :post_comments, dependent: :destroy

	validates :title, presence: true, length: { in: 1..200 }
	validates :body, presence: true, length: { in: 1..200 }
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books, dependent: :destroy
         has_many :post_comments, dependent: :destroy
         attachment :profile_image

         validates :name, uniqueness: true, length: { in: 2..20 }
         validates :introduction, length: { maximum: 50 }

         def email_required?
         	false
         end
         def email_changed?
         	false
         end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def after_sign_in_path_for(resource)
		user_path(current_user.id)
	end

	def after_sign_out_path_for(resource)
		root_path
	end

	before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!, only: [:new, :create, :index, :show, :edit, :update, :destroy]
before_action :correct_user, only: [:edit, :update]

	def top
		flash[:success] = 'Signed out successfully'
	end

	def about
	end

	def new
		@book = Book.new
	end

	def create
		@user = User.new
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
		redirect_to book_path(@book)
	else
		render :index
	end
	    flash[:success] = 'Book was successfully created.'
	end

	def index
		@user = User.new
		@book = Book.new
		@books = Book.page(params[:book]).reverse_order
		@users = User.all
	end

	def show
		@books = Book.new
		@book = Book.find(params[:id])
		@user = User.find(@book.user_id)
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		book = Book.new(book_params)
		@book = Book.find(params[:id])
		@book.user_id = current_user.id
		if @book.update(book_params)
		 redirect_to book_path(@book.id)
		else
			render :index
		end
		flash[:success] = 'Book was successfully updated.'
	end

	def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to books_path
	end

	private
	def book_params
		params.require(:book).permit(:title, :body)
	end
	def correct_user
		@book = Book.find(params[:id])
		if current_user != @book.user
			redirect_to books_path
		end
    end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
  end

  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
before_action :correct_user, only: [:edit, :update]

def index
	@user = current_user
	@users = User.page(params[:id]).reverse_order
	@book = Book.new
	@books = Book.all
end

def show
	@book = Book.new
	@user = User.find(params[:id])
	@books = @user.books.page(params[:page]).reverse_order
end

def edit
	@user = User.find(params[:id])
end

def update
	@user = User.find(params[:id])
	@user.update(user_params)
	redirect_to user_path(@user.id)
	flash[:success] = 'mydate was successfully update.'
	flash[:error] = 'error'
end

private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  def correct_user
	@user = User.find(params[:id])
	if current_user != @user
		redirect_to user_path(current_user.id)
	end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<% if book.errors.any? %>
<div id="error_explanation">
  <h2><%= book.errors.count %>errors prohibited this obj from being saved</h2>
  <ul>
   <% book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
   <% end %>
  </ul>
<% end %>

<div class="body">
  <div class="container">
    <div class="flash">
  <% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
</div>

    <div class="container">
      <div class="row">
        <div class="col-xs-3">
          <h2>User Info</h2>
              <div class="user-image">
                <%= attachment_image_tag current_user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %>
              </div>
              <table class="table table-striped">
                <tbody>
                  <tr>
                    <th>name</th>
                    <th><%= @user.name %></th>
                  </tr>
                  <tr>
                    <th>introduction</th>
                    <th><%= @user.introduction %></th>
                  </tr>
                </tbody>
              </table>

              <div class="row">

                <% if @user.id == current_user.id %>
                <p><%= link_to "", edit_user_path(current_user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit" %>
              </p>
                <% else %>
                <p><%= link_to "", user_path(current_user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit" %>
              </p>
              <% end %>
              </div>

            <h2>New book</h2>
                <%= form_for (book) do |f| %>

                  <h4>Title</h4>
                  <%= f.text_field :title %>

                  <h4>Opinion</h4>
                  <%= f.text_field :body %>

                  <input type="submit" name="commit" value="Create Book" class="btn  btn-primary col-xs-12" data-disable-with="Create Book">

                <% end %>
            </div>

app/views/books/about.html.erb
<div class="body">
	<div class="container">
		<h1>Welcome to
			<span class="glyphicon glyphicon-book">
			</span>
			<storng>Bookers</storng>
			!
		</h1>
	</div>
</div>

app/views/books/edit.html.erb
<div class="body">
	<div class="container">
		<div class="row">
<div class="col-md-6 col-md-offset-3">
<h1>Editing Book</h1>
<%= form_for(@book) do |f| %>
<div class="field row">
<h4 class="title">Title</h4>
<%= f.text_field :title %>
</div>
<div class="field row">
<h4 class="title">Opinion</h4>
<%= f.text_field :body %>
</div>
<div class="action row">
<input type="submit" name="commit" value="Update Book" class="btn btn-primary col-xs-12" data-disable-with="Update Book">
</div>
<% end %>

<%= link_to "Show", book_path(@book) %>
|
<%= link_to "Back", books_path %>
</div>
</div>
</div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
<div id="error_explanation">
  <h2><%= @book.errors.count %>errors prohibited this obj from being saved</h2>
  <ul>
   <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
   <% end %>
  </ul>
<% end %>

<div class="flash">
  <% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>

    <div class="container">
      <div class="row">
        <div class="col-xs-3">
          <h2>User Info</h2>
              <div class="user-image">
                <%= attachment_image_tag current_user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %>
              </div>
              <table class="table table-striped">
                <tbody>
                  <tr>
                    <th>name</th>
                    <th><%= current_user.name %></th>
                  </tr>
                  <tr>
                    <th>introduction</th>
                    <th><%= current_user.introduction %></th>
                  </tr>
                </tbody>
              </table>

              <div class="row">
                <p><%= link_to "", edit_user_path(current_user), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench edit" %>
              </p>
              </div>

            <h2>New book</h2>
                <%= form_for (@book) do |f| %>

                  <h4>Title</h4>
                  <%= f.text_field :title %>

                  <h4>Opinion</h4>
                  <%= f.text_field :body %>

                 <input type="submit" name="commit" value="Create Book" class="btn  btn-primary col-xs-12" data-disable-with="Create Book">

                <% end %>
            </div>


<div class="col-xs-9">
  <h2>Books</h2>
  <table class="table table-striped">
  <thead>
  	<tr>
  		<th></th>
  		<th>Title</th>
  		<th>Opinion</th>
  		<th colspan="3"></th>
  	</tr>
  </thead>
  <tbody>
    <% if @books.present? %>
  	<% @books.each do |book| %>
  	<tr>
  		<td><%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size: "30x30" %>
  		</td>
  		<td><%= link_to "#{book.title}", book_path(book.id) %>
  		</td>
  		<td><%= book.body %>
  		</td>
  	</tr>
  	<% end %>
    <% end %>
  </tbody>
</table>
</div>

app/views/books/new.html.erb
<%= render 'books/list', book:@book %>

<div class="col-xs-9">
	<h2>Books</h2>
	<table class="table table-striped">
		<thead>
			<tr>
				<th></th>
				<th>Title</th>
				<th>Opinion</th>
				<th colspan="3"></th>
			</tr>
		</thead>
		<tbody>
			<% @book.each do |book| %>
			<tr>
			<td><% attachment_image_tag book_user, :profile_image, :fill, 10, 10, fallback: "no_image.jpg" %>
			</td>
			<td><%= link_to "#{book.title}", book_path(book.id) %>
			</td>
			<td><%= book.body %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>

app/views/books/show.html.erb
<% if @book.errors.any? %>
<div id="error_explanation">
  <h2><%= @book.errors.count %>errors prohibited this obj from being saved</h2>
  <ul>
   <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
   <% end %>
  </ul>
<% end %>

<div class="flash">
  <% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>

    <div class="container">
      <div class="row">
        <div class="col-xs-3">
          <h2>User Info</h2>
              <div class="user-image">
                <%= attachment_image_tag current_user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg" %>
              </div>
              <table class="table table-striped">
                <tbody>
                  <tr>
                    <th>name</th>
                    <th><%= @user.name %></th>
                  </tr>
                  <tr>
                    <th>introduction</th>
                    <th><%= @user.introduction %></th>
                  </tr>
                </tbody>
              </table>

              <div class="row">

                <% if @user.id == current_user.id %>
                <p><%= link_to "", edit_user_path(current_user), class:"col-xs-12 btn btn-default glyphicon-wrench edit" %>
              </p>
                <% elsif @user.id != current_user.id %>
                <p><%= link_to "", user_path(current_user), class:"col-xs-12 btn btn-default glyphicon-wrench edit" %>
              </p>
              <% end %>
              </div>

            <h2>New book</h2>
                <%= form_for (@books) do |f| %>

                  <h4>Title</h4>
                  <%= f.text_field :title %>

                  <h4>Opinion</h4>
                  <%= f.text_field :body %>

                  <%= f.submit 'Create Book' %>

                <% end %>
            </div>


<div class="col-xs-9">
  <h2>Book detail</h2>
  <table class="table table-striped">
    <tbody>
      <tr>
        <td><%= attachment_image_tag @book.user, :profile_image, fallback: "no_image.jpg", size: "30x30" %><br>
          <%= link_to "#{@user.name}", user_path(@user.id) %>
      </td>
      <td><%= link_to "#{@book.title}", book_path(@book.id) %>
      </td>
      <td><%= @book.body %></td>
      <% if @user == current_user %>
      <td><%= link_to "Edit", edit_book_path(@book), class:"btn-sm btn-success" %></td>
      <td><%= link_to "Destroy", book_path(@book), method: :delete, class:"btn-sm btn-danger" %></td>
      <% end %>
      </tr>
    </tbody>
  </table>
</div>

app/views/books/top.html.erb
<div class="body">
	<div class="container">
		<div class="flash">
  <% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
</div>
		<div class="row">
		 <div class="top-message col-md-offset-3 col-md-6">
		  <h1>welcome to
		  <span class="glyphicon glyphicon-book">
		  	<strong>Bookers</strong>
		  	!!
		  </span>
		  </h1>
		  <p>In
		  	<span class="glyphicon glyphicon-book"></span>
		  	<strong>Bookers</strong>
		  	,
		  </p>
		  <p>you can share and exchange your opinions , inpressions , and emotions</p>
		  <p>about various books!</p>
		  <div class="btn-wrapper">
		  	<div class="row">
		  		<p>
		  		<a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a>
		  	</p>
		  	</div>
		  	<div class="row">
		  		<p>
		  			<a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a>
		  		</p>
		  	</div>
		  </div>
		</div>
	</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<header>
      <div class="container clearfix">
        <nav class="navbar-left">
          <span class="title">Bookers</span>
        </nav>

        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li class="list">
            <%= link_to "Home", user_path(current_user.id), class:"glyphicon glyphicon-home home" %>
          </li>
          <li class="list">
            <%= link_to "Users", users_path, class:"glyphicon glyphicon-user users" %>
          </li>
          <li class="list">
            <%= link_to "Books", books_path, class:"glyphicon glyphicon-book books" %>
          </li>
          <li class="list">
            <%= link_to "logout", destroy_user_session_path, class:"glyphicon glyphicon-log-out logout" ,method: :delete %>
          </li>
          <% else %>
          <li>
            <a class="glyphicon glyphicon-home home" href="/">
            Home</a>
          </li>
          <li>
            <a class="glyphicon glyphicon-link about" href="/home/about"> About</a>
          </li>
          <li>
            <a class="glyphicon glyphicon-edit sign_up" href="/users/sign_up"> sign up</a>
          </li>
          <li>
            <a class="glyphicon glyphicon-log-in sign_in" href="/users/sign_in"> login</a>
          </li>
          <% end %>
        </ul>
        </nav>
      </div>
    </header>

    <%= yield %>
  </body>
</html>

app/views/post_comments/create.html.erb
<h1>PostComments#create</h1>
<p>Find me in app/views/post_comments/create.html.erb</p>

app/views/post_comments/edit.html.erb
<h1>PostComments#edit</h1>
<p>Find me in app/views/post_comments/edit.html.erb</p>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= @user.errors.count %>errors prohibited this obj from being saved</h2>
  <ul>
   <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
   <% end %>
  </ul>
<% end %>

<h2>User info</h2>
<%= form_for(@user) do |f| %>
<h4 class="title">Name
<%= f.text_field :name %></h4>
<div class="form-group has-icon">
	<div class="user-edit-image">
		<h4 class="profile">Image</h4>
		<%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg" %>
	</div>
	<%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
<h4 class="title">Introduction</h4>
<%= f.text_field :introduction %>
<br>
<div class="submit">
<%= f.submit 'Update User' %>
</div>
<% end %>

app/views/users/index.html.erb
<%= render 'books/list', book: @book %>

<div class="col-xs-9">
  <h2>Users</h2>
  <table class="table table-striped">
  <thead>
  	<tr>
  		<th>image</th>
  		<th>name</th>
  		<th colspan="3"></th>
  	</tr>
  </thead>
  <tbody>
  	<% @users.each do |user| %>
  	<tr>
  		<td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "30x30" %>
  		</td>
  		<td><%= user.name %></td>
  		<td><%= link_to "Show", user_path(user.id) %></td>
  	</tr>
  	<% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<%= render 'books/list', book: @book %>


<div class="col-xs-9">
  <h2>Books</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% if @books.present? %>
      <% @books.each do |book| %>
      <tr>
      <td><%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size: "30x30" %>
      </td>
      <td><%= link_to "#{book.title}", book_path(book.id) %>
      </td>
      <td><%= book.body %></td>
      <td></td>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>